[package]
name = "video-processing"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
bcrypt = "0.17.0"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-async-std"] }
